### ISSUE TITLE
Gather all necessary cryptocurrency network information

### ISSUE THREAD

**Issue by szerepak** [Lamden/clove#2]
We need:
- name of the cryptocurrency
- symbols
- default symbol
- dns addressess of seed nodes
- port number
- rpc port number
- test network dns addressess of seed nodes and port, rpc port number

**Comment by StuartFarmer** [comment]
Here are the bootnodes for Ethereum: https://github.com/ethereum/go-ethereum/blob/ff2c966e7f0550f4c0cb2b482d1af3064e6db0fe/params/bootnodes.go

I'm pretty sure you can just scrap the IP addresses from here and then use the Web3py library as a connection to push transactions.

**Comment by StuartFarmer** [comment]
@olaczerepak found some ZClassic nodes from an issue that's over a year old so they might not work. However, it could be better than nothing: https://github.com/z-classic/zclassic/issues/5

**Comment by szerepak** [comment]
@StuartFarmer As we're now focused on the BTC based chains, I'll leave the Ethereum thing for the "to do" issue. Moving this one to done. Thanks for the bootnodes!
