### ISSUE TITLE
Publishing atomic_swap returns TxHash which is never found on kovan network

### ISSUE THREAD

**Issue by shoutcool** [Lamden/clove#211]
i am using clove version (installed with pip):
> Name: clove
> Version: 1.1.2

and i have following code: 

According to the tutorial the `approve_token` function was called before, and the transaction was sucessfully published and mined by kovan network within seconds. 

The problem seems to be the publishing of the atomic_swap:

```
initial_transaction = eth_test.atomic_swap(
    alice_address,
    bob_address,
    alice_spending_tokens,
    token_address=alice_spending_token_address
)
initial_transaction.sign(alice_private_key)
print(initial_transaction.show_details())

tx_id = initial_transaction.publish()
print("Transaction ID: %s" % (tx_id)) 
```

the transaction id returned by clove is: 0x25d3ef058fe46ca68e8f72a97fdef6c38e747fd877ef4c1fa723efc95c55b0ef

But there is no such transaction on the kovan network.
https://kovan.etherscan.io/tx/0x25d3ef058fe46ca68e8f72a97fdef6c38e747fd877ef4c1fa723efc95c55b0ef

see the logs below for further information:

> 2018-06-28 20:26:01 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 232
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 232
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 104
> 2018-06-28 20:26:02 MacBook-Pro.local root[13131] DEBUG Token get from contract with success
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 41
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 49
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 39
> {'nonce': 4, 'gasprice': 15000000000, 'to': '0x7657ca877fac31d20528b473162e39b6e152fd2e', 'value': Decimal('3'), 'data': '0x52f50db7000000000000000000000000000000000000000000000000000000005b37cb3a483af29342963e95d0fbea3ece3069cc53429f5700000000000000000000000000000000000000000000000072adc2a0e37f91fe7e257cb2e1fe178ec7d12a79000000000000000000000000b18845c260f680d5b9d84649638813e342e4f8c900000000000000000000000000000000000000000000000029a2241af62c0000', 'v': 27, 'r': 20819866298769625551287166195308273950199721290168678972924253341772776630332, 's': 3380231710767523351451808891624590629892181573821129978856161746180579352869, 'sender': '0x6c29b73fb04d41e3c11d230fdb08554420916f79', 'transaction_address': '0x25d3ef058fe46ca68e8f72a97fdef6c38e747fd877ef4c1fa723efc95c55b0ef', 'gas_limit': 300000, 'transaction': '0xf9010a0485037e11d600830493e0947657ca877fac31d20528b473162e39b6e152fd2e80b8a452f50db7000000000000000000000000000000000000000000000000000000005b37cb3a483af29342963e95d0fbea3ece3069cc53429f5700000000000000000000000000000000000000000000000072adc2a0e37f91fe7e257cb2e1fe178ec7d12a79000000000000000000000000b18845c260f680d5b9d84649638813e342e4f8c900000000000000000000000000000000000000000000000029a2241af62c00001ba02e07a07151a0d821b2433df8c7d59a16e0df1f9388af483ff57461009f8e683ca0077924b285f5642bf7c0e8dd7d1c3fbcd410ed7ecceb97a281b210a4f3d56125', 'recipient_address': '0x72ADc2a0e37f91Fe7e257cb2e1FE178Ec7D12A79', 'value_text': '3.000000000000000000 REP', 'secret': 'c015feb06664968caf40576e3ede3993cf98ff1e0f3f8fe06c522768828cc9b3', 'secret_hash': '483af29342963e95d0fbea3ece3069cc53429f57', 'locktime': datetime.datetime(2018, 6, 30, 18, 26, 2, 198783), 'sender_address': '0x6c29b73fb04D41e3c11D230fdB08554420916F79', 'contract_address': '0x7657Ca877Fac31D20528B473162E39B6E152fd2e', 'refund_address': '0x6c29b73fb04D41e3c11D230fdB08554420916F79', 'token_address': '0xB18845c260F680d5B9D84649638813E342E4F8C9'}
> 2018-06-28 20:26:02 MacBook-Pro.local urllib3.connectionpool[13131] DEBUG https://kovan.infura.io:443 "POST /api-key HTTP/1.1" 200 104
> 2018-06-28 20:26:02 MacBook-Pro.local root[13131] DEBUG Transaction 0x25d3ef058fe46ca68e8f72a97fdef6c38e747fd877ef4c1fa723efc95c55b0ef published successful
> Transaction ID: 0x25d3ef058fe46ca68e8f72a97fdef6c38e747fd877ef4c1fa723efc95c55b0ef

btw: the variables are set as:
```
alice_address = '0x6c29b73fb04D41e3c11D230fdB08554420916F79'
alice_spending_tokens = '3' #Alice wants 2 MKR (and is spending 3 REP)
alice_spending_token_address = '0xB18845c260F680d5B9D84649638813E342E4F8C9' #REP Contract Address

bob_address = '0x72ADc2a0e37f91Fe7e257cb2e1FE178Ec7D12A79' 
```

**Comment by trojkat** [comment]
@shoutcool this is a known behavior of web3 when the transaction is signed with a wrong private key there is no exception raised when publishing. Are you sure that you used the right private key?

**Comment by shoutcool** [comment]
@trojkat i took the code from clove documentation. so i don't think i am using the wrong private key. I just attached the full source code (without private key values). Because alice has to initiate the atomic swap, the transaction needs to be signed with her private key IMO.

```
from clove.network import EthereumTestnet

eth_test = EthereumTestnet()

alice_address = '0x6c29b73fb04D41e3c11D230fdB08554420916F79'
alice_private_key = 'xy'

alice_spending_tokens = '3' #Alice wants 2 MKR (and is willing to spend 3 REP)
alice_spending_token_address = '0xB18845c260F680d5B9D84649638813E342E4F8C9' #REP Contract Address

bob_address = '0x72ADc2a0e37f91Fe7e257cb2e1FE178Ec7D12A79' 
bob_private_key = 'zz'

bob_spending_tokens = 2 #Bob wants 3 REP (and is willing to spend 2 MKR)
bob_speding_tokens_address = '0x1Dad4783cf3fe3085C1426157aB175A6119A04bA' #MKR Contract Address

# To send tokens to an atomic swap contract Alice has to first approve 
# that the tokens she own can be spend by that contract.
approve_transaction = eth_test.approve_token(alice_address, alice_spending_tokens, alice_spending_token_address)
approve_transaction.sign(alice_private_key)
print(approve_transaction.show_details())

tx_id = approve_transaction.publish() #Here everything works fine: Tx is found on kovan testnet
print("Transaction ID: %s" % (tx_id)) 

# Alice is initializing an atomic swap transaction
initial_transaction = eth_test.atomic_swap(
    alice_address,
    bob_address,
    alice_spending_tokens,
    token_address=alice_spending_token_address
)
initial_transaction.sign(alice_private_key)
print(initial_transaction.show_details())

tx_id = initial_transaction.publish() #Here is the issue: Returned Tx does not exist on kovan testnet
print("Transaction ID: %s" % (tx_id)) 
```

**Comment by trojkat** [comment]
@shoutcool Hmm... Looks good to me. I did the same with our test token.

```
from clove.network import EthereumTestnet
from clove.network.ethereum.wallet import EthereumWallet

eth_test = EthereumTestnet()
alice_wallet = EthereumWallet('ALICE_PRIVATE_KEY')
alice_spending_tokens = 3
bbt = eth_test.get_token_by_address('0x53E546387A0d054e7FF127923254c0a679DA6DBf')
alice_approve_transaction = eth_test.approve_token(
    alice_wallet.address, 
    alice_spending_tokens, 
    bbt.token_address,
)
alice_approve_transaction.sign(alice_wallet.private_key)
alice_approve_transaction.publish()
``` 

[0xa0f8881b5d5e5d2f938b756c077afa5640f007d79d949f8f34346ed3c912e804](https://kovan.etherscan.io/tx/0xa0f8881b5d5e5d2f938b756c077afa5640f007d79d949f8f34346ed3c912e804)


```
bob_address = '0xd867f293Ba129629a9f9355fa285B8D3711a9092'
initial_transaction = eth_test.atomic_swap(
    alice_wallet.address, 
    bob_address, 
    alice_spending_tokens, 
    token_address=bbt.token_address,
)
initial_transaction.sign(alice_wallet.private_key)
initial_transaction.publish()
```
[0x9749122c0b21f919f49b059d600e1e0291be407cf0eb010ed79976ff28279719](https://kovan.etherscan.io/tx/0x9749122c0b21f919f49b059d600e1e0291be407cf0eb010ed79976ff28279719)

```
tx = eth_test.audit_contract('0x9749122c0b21f919f49b059d600e1e0291be407cf0eb010ed79976ff28279719')
tx.show_details()
{'contract_address': '0x7657Ca877Fac31D20528B473162E39B6E152fd2e',
 'locktime': datetime.datetime(2018, 7, 29, 7, 55, 20),
 'recipient_address': '0xd867f293Ba129629a9f9355fa285B8D3711a9092',
 'refund_address': '0x999F348959E611F1E9eab2927c21E88E48e6Ef45',
 'secret_hash': 'de978dab9b024d4edc9956daa7806148e34425b2',
 'token_address': '0x53E546387A0d054e7FF127923254c0a679DA6DBf',
 'transaction_address': '0x9749122c0b21f919f49b059d600e1e0291be407cf0eb010ed79976ff28279719',
 'value': Decimal('3'),
 'value_text': '3.000000000000000000 BBT'
```
