### ISSUE TITLE
Getting current fee estimates

### ISSUE THREAD

**Issue by trojkat** [Lamden/clove#27]
## The Problem

* When creating a transaction we have to know the current fee value in the network to be able to create a transaction that will be included in the next block because with atomic swaps time matters.
* Bitcoin nodes may also set the [FeeFilter](https://bitcoin.org/en/developer-reference#feefilter) and do not accept transactions with fee rate lower than a specific value so again we need to set the right fee.
* There is no way to get fee estimates using bitcoin P2P network protocol.

## Solution 1

Use 3rd party API (like [blockcypher.com](https://live.blockcypher.com/btc/)) to get the current fee estimates.

```
In [1]: import requests

In [2]: r = requests.get('https://api.blockcypher.com/v1/btc/main').json()

In [3]: r
Out[3]: 
{'hash': '0000000000000000004e6a1ac1a65bfa801ad6b66d1641f2922311a410e176d1',
 'height': 507242,
 'high_fee_per_kb': 200801,
 'last_fork_hash': '00000000000000000055580862147720e31c3a8b80add74b0a77059a66051897',
 'last_fork_height': 505504,
 'latest_url': 'https://api.blockcypher.com/v1/btc/main/blocks/0000000000000000004e6a1ac1a65bfa801ad6b66d1641f2922311a410e176d1',
 'low_fee_per_kb': 200801,
 'medium_fee_per_kb': 200801,
 'name': 'BTC.main',
 'peer_count': 994,
 'previous_hash': '0000000000000000002bfae8c31731a572ce468c92957ada699e6ce69bf25bba',
 'previous_url': 'https://api.blockcypher.com/v1/btc/main/blocks/0000000000000000002bfae8c31731a572ce468c92957ada699e6ce69bf25bba',
 'time': '2018-02-02T09:35:58.567625786Z',
 'unconfirmed_count': 13622}
```
#### Summary

💚  easy to use
💚  no additional services to maintain
💩  there are always some rate limits and paid plans with tokens
💩  our tool will have to rely on some 3rd party service
💩  a small number of supported networks

## Solution 2

Clove user will have to have running nodes for every network that he is going to use for atomic swap. Then Clove can communicate with those nodes via RPC commands.

#### Summary

💚  good support for most networks because most clients have RPC interface
💚  you don't have to rely on 3rd party services
💚  with RPC we can use commands like [fundrawtransaction](https://bitcoin.org/en/developer-reference#fundrawtransaction) or [signrawtransaction](https://bitcoin.org/en/developer-reference#signrawtransaction) to get things done quickly
💩  a user will have install, configure and run additional software on his system
💩  if you want to use 5 networks for atomic swaps you will need 5 nodes running on your machine
💩  additional setup is needed in Clove to configure access to every node via RPC (port, user, password)

## Solution 3

Build our public API and provide needed data from other networks by running a node for each network or getting data from other sources (like blockcypher.com) and cache them. Clove will have hardcoded address for our API.

#### Summary

💚  a user won't need to run nodes on his machine
💚  a large number of supported networks
💩  we will have to maintain a new service
💩  a user will have to rely on 3rd party service

**Comment by StuartFarmer** [comment]
For solution 2... will they have to sync with the network and store blockchain data?

If not, this could be a possibility.

Otherwise, it might make sense for us to ultimately work towards solution 3 because it will probably benefit us in the long term to have our own full nodes but use solution 1 to 'cheat' it until then.

I'll think about this more throughout the day.

**Comment by trojkat** [comment]
Yes, they have to sync with the network. In case of Bitcoin, there is a way to set [pruning](https://bitcoin.org/en/release/v0.12.0#wallet-pruning) and use only around 2GB of disc space but this is probably not available in other bitcoin-based networks.
