### ISSUE TITLE
Setup Travis CI for this repo

### ISSUE THREAD

**Issue by trojkat** [Lamden/clove#5]
Configuration for private projects:
https://docs.travis-ci.com/user/travis-pro/

`.travis.yml` file will be available after merging #4

**Comment by StuartFarmer** [comment]
Ok, I purchased the pro version for a single concurrent job at the moment. That should be enough to get us going. This organization previously had Travis CI setup for our https://github.com/lamden/saffron repo so my token has already been added. However, this was on the free one. I didn't see any information on the page you linked that I need to do anything different, though so I'm assuming it's good to go?

Let me know if there's something else to do before we close this issue.

**Comment by trojkat** [comment]
Thanks @StuartFarmer ! Travis is working as expected.
